version: 2.1
orbs: 
  aws-eks: circleci/aws-eks@2.1.1
  kubernetes: circleci/kubernetes@1.3.0
jobs:
  lint:
    docker:
      - image: python:3.9-alpine
    steps:
      - checkout
      - run:
          name: Install make
          command: |
            apk add make
      - run:
          name: Install linters
          command: |
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            pip install flake8
      - run:
          name: Run lint
          command: |
            make lint

  build-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.11"
          docker_layer_caching: true
      - run:
          name: Build docker container
          command: |
            export DOCKER_BUILDKIT=1
            docker build . --tag=capstone-fastapi
      - run:
          name: Docker login
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASS}
      - run:
          name: Tag and push
          command: |
            docker tag capstone-fastapi ${DOCKER_USER}/capstone-fastapi
            docker push ${DOCKER_USER}/capstone-fastapi

  update-kube-cluster:
    docker:
      - image: cimg/python:3.8
    parameters:
      cluster-name:
        description: Name of the cluster
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: Test service
          command: |
            kubectl get services
      - run:
          name: Rolling update
          command: |
            kubectl rollout restart deploy/capstone-fastapi


workflows:
  default:
    jobs:
      - lint
      - build-docker:
          requires: [lint]
      - update-kube-cluster:
          cluster-name: capstone
          requires: [build-docker]
