version: 2
jobs:
  lint:
    docker:
      - image: python:3.9-alpine
    steps:
      - checkout
      - run:
          name: Install make
          command: |
            apk add make
      - run:
          name: Install linters
          command: |
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            pip install
      - run:
          name: Run lint
          command: |
            make lint

workflows:
  default:
    jobs:
      - lint
      # - build-docker
      # - test-frontend:
      #     requires: [build-frontend]
      # - test-backend:
      #     requires: [build-backend]
      # - scan-backend:
      #     requires: [build-backend]
      # - scan-frontend:
      #     requires: [build-frontend]
      # - deploy-infrastructure:
      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
      #     filters:
      #       branches:
      #         only: [master]